### ISSUE TITLE
啥时候支持nb4，被迫升级了

### ISSUE THREAD

**Issue by liuzj288** [NekoAria/YetAnotherPicSearch#10]

**Comment by liuzj288** [comment]
兼容吗？升级之后搜图寄了

**Comment by NekoAria** [comment]
> 兼容吗？升级之后搜图寄了

有截图或者日志吗？
没有我也没法排查问题啊。
还有安装插件的方式。

**Comment by NekoAria** [comment]
> 以前nb2能搜出结果的，现在直接报错 ![image](https://user-images.githubusercontent.com/13833404/176940028-d5354dbc-7d8a-492a-ab44-30f3bbdbfb5d.png) ![image](https://user-images.githubusercontent.com/13833404/176940137-3e1d835e-0658-45c6-9e9e-5ab5a9eaab72.png)

第一张截图里的报错是因为依赖升级，你更新依赖就行了。
然后再看看还会不会遇到第二张截图里的报错信息。
