### ISSUE TITLE
google搜索不到内容

### ISSUE THREAD

**Issue by veadex** [NekoAria/YetAnotherPicSearch#102]
### YetAnotherPicSearch 、 PicImageSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

全是最新的

### 列出安装的 Python 包

通过nb_cli安装

### 如何复现

搜索图片，使用搜图--purge--google，返回为空，但是点击链接之后发现是有搜索内容的
链接`https://yww.uy/Pg4wfN`
图片
![Screenshot_2023-07-23-14-51-53-020_com tencent mobileqq](https://github.com/NekoAria/YetAnotherPicSearch/assets/65024689/234376c6-5cd7-4f09-97af-344edbd25873)
![Screenshot_2023-07-23-14-52-09-974_com android chrome](https://github.com/NekoAria/YetAnotherPicSearch/assets/65024689/cf240205-0159-4207-83c1-c91e492e1eb5)
![Cache_16410ae9b97903b8](https://github.com/NekoAria/YetAnotherPicSearch/assets/65024689/21d57b4e-e452-4593-ba85-6c4ea63fc45c)

### 期望行为

正确搜索到内容并返回

### 实际行为

网页搜索到了内容，但是返回为搜索到

**Comment by veadex** [comment]
使用了代理

**Comment by NekoAria** [comment]
更新 PicImageSearch 到最新的 v3.9.5 ，应该就没问题了。

**Comment by veadex** [comment]
可以了₍˄·͈༝·͈˄*₎◞ ̑̑
