### ISSUE TITLE
功能改进：转发昵称调用全局nickname

### ISSUE THREAD

**Issue by Blue-Roar** [NekoAria/YetAnotherPicSearch#11]
算是个无关紧要的小功能吧
构建函数是__init__.py下的send_forward_msg，默认name现在似乎是个幽灵字符
环境变量里NICKNAME应该都有设置的吧……

**Comment by NekoAria** [comment]
其实是故意的，出于一定程度上的隐私保护。

**Comment by NekoAria** [comment]
你如果想要如实呈现机器人的昵称，那我也可以加个开关来配置这个。

**Comment by NekoAria** [comment]
真要说是我自己有点被害妄想吧，比如搜图结果被人转发到其他地方什么的（

**Comment by NekoAria** [comment]
已更新 `v1.5.11` 。
