### ISSUE TITLE
qq群近期对yande的链接与saucenao的链接进行了屏蔽处理

### ISSUE THREAD

**Issue by ankoconmf** [NekoAria/YetAnotherPicSearch#118]
### 功能需求

大佬能否将这俩条链接加入到处理的红链网址列表里呢

### 理由

qq群近期对yande，yandex的链接与saucenao的链接进行了屏蔽处理
![测试](https://github.com/NekoAria/YetAnotherPicSearch/assets/71115755/ae8508fd-6698-4921-ac67-59457cc0e699)
![测试2](https://github.com/NekoAria/YetAnotherPicSearch/assets/71115755/24fd787f-8bc8-4739-ade7-c08ff1d4e4d2)

**Comment by NekoAria** [comment]
其实 `to_confuse_urls` 可以自定义的，参照 [config.py](https://github.com/NekoAria/YetAnotherPicSearch/blob/main/YetAnotherPicSearch/config.py) ，要配置的话，需要保留原有的部分，然后添加。

我后续写到 README.md 里吧。
