### ISSUE TITLE
建议在群聊中实现直接回复 图片 即可搜索

### ISSUE THREAD

**Issue by liuzj288** [NekoAria/YetAnotherPicSearch#12]
这样就不用再手动保存图片再发一次了

**Comment by NekoAria** [comment]
直接回复带图片的消息，再艾特机器人不就可以搜索吗？
还是说你想要什么样的效果？

**Comment by NekoAria** [comment]
或许你指的是回复机器人的消息？

`群里回复机器人发送的消息时，必须带上 "再搜"才会搜图，否则会被无视`

**Comment by liuzj288** [comment]
要艾特啊，我试试
