### ISSUE TITLE
配置SAUCENAO_KEY的情况下无法使用SAUCENAO正常搜图

### ISSUE THREAD

**Issue by SEAFHMC** [NekoAria/YetAnotherPicSearch#130]
### YetAnotherPicSearch 、 PicImageSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

YetAnotherPicSearch版本: 1.9.6
PicImageSearch版本: 3.9.7
协议端: Lagrange
nonebot版本: 2.2.1
python版本: 3.10.12

### 列出安装的 Python 包

aioconsole==0.7.0
aiofiles==23.2.1
annotated-types==0.6.0
anyio==3.7.1
APScheduler==3.10.4
arclet-alconna==1.8.6
arclet-alconna-tools==0.7.1
arrow==1.3.0
bbcode==1.1.0
binaryornot==0.4.4
cachetools==5.3.3
cashews==6.4.0
certifi==2024.2.2
chardet==5.2.0
charset-normalizer==3.3.2
ChatGPTWeb==0.2.15
click==8.1.7
contourpy==1.2.0
cookiecutter==2.6.0
cssselect==1.2.0
cycler==0.12.1
dateparser==1.2.0
distlib==0.3.8
emoji==2.10.1
exceptiongroup==1.2.0
fastapi==0.110.0
filelock==3.13.1
filetype==1.2.0
fonttools==4.50.0
greenlet==3.0.3
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==1.0.4
httptools==0.6.1
httpx==0.25.2
hyperframe==6.0.1
idna==3.6
Jinja2==3.1.3
kiwisolver==1.4.5
loguru==0.7.2
lxml==4.9.4
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.8.3
mdurl==0.1.2
meme-generator==0.0.18
more-itertools==10.2.0
msgpack==1.0.8
multidict==6.0.5
nb-cli==1.4.0
nepattern==0.6.5
nonebot-adapter-onebot==2.4.3
nonebot-adapter-qq==1.4.2
nonebot-plugin-alconna==0.41.1
nonebot-plugin-apscheduler==0.4.0
nonebot-plugin-gpt==0.0.12
nonebot-plugin-htmlrender==0.3.1
nonebot-plugin-localstore==0.6.0
nonebot-plugin-sendmsg-by-bots==0.1.3
nonebot2==2.2.1
nonebot_plugin_memes==0.6.2
nonebot_plugin_session==0.3.1
nonebot_plugin_userinfo==0.2.3
noneprompt==0.1.9
numpy==1.26.4
OpenAIAuth==3.0.0
opencv-python-headless==4.9.0.80
packaging==24.0
PicImageSearch==3.9.7
pil-utils==0.1.10
pillow==10.2.0
platformdirs==4.2.0
playwright==1.42.0
playwright-stealth==1.0.6
prompt-toolkit==3.0.43
pydantic==1.10.14
pydantic_core==2.16.3
pyee==11.0.1
pyfiglet==1.0.2
Pygments==2.17.2
pygtrie==2.5.0
pymdown-extensions==10.7.1
pyparsing==3.1.2
pypinyin==0.51.0
pyquery==2.0.0
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-markdown-math==0.8
python-multipart==0.0.6
python-slugify==8.0.4
pytz==2024.1
PyYAML==6.0.1
regex==2023.12.25
requests==2.31.0
rich==13.7.1
shelved-cache==0.3.1
six==1.16.0
sniffio==1.3.1
starlette==0.36.3
StrEnum==0.4.15
tarina==0.4.4
tenacity==8.2.3
text-unidecode==1.3
tls-client==1.0.1
toml==0.10.2
tomli==2.0.1
tomlkit==0.12.4
types-python-dateutil==2.9.0.20240316
typing_extensions==4.10.0
tzlocal==5.2
urllib3==2.2.1
uvicorn==0.29.0
uvloop==0.19.0
virtualenv==20.25.1
watchfiles==0.21.0
wcwidth==0.2.13
websockets==12.0
yarl==1.9.4
YetAnotherPicSearch @ file:///home/alwyzon/YetAnotherPicSearch
# 
YetAnotherPicSearch是在github上clone下来手动安装的，安装时lxml和httpx版本与PicImageSearch要求的版本冲突所以修改了一下
![JDM_ZO8IV8K6EJVYQFNJ5H9](https://github.com/NekoAria/YetAnotherPicSearch/assets/9484642/5f48991e-9ba5-467d-a155-b4590a00e419)
![T IS_9QDE~XN5YC)%7(9J09](https://github.com/NekoAria/YetAnotherPicSearch/assets/9484642/8ae49884-7d15-4537-b07f-d00693ca83ee)

### 如何复现

发送/搜图后再发送图片

### 期望行为

以SAOCENAO模式进行搜图，希望有配置可以选择是否选用合并转发搜图结果

### 实际行为

显示使用Ascii2D模式搜图但并没有搜
![image](https://github.com/NekoAria/YetAnotherPicSearch/assets/9484642/2801e6bf-150a-4f34-a529-17e8fca0d7ca)
.env配置如下:
![image](https://github.com/NekoAria/YetAnotherPicSearch/assets/9484642/4808f613-23d2-41de-8370-c79c217abda3)
聊天截图如下:
![_X`LR(}) YG%K@`D2B_GPG7](https://github.com/NekoAria/YetAnotherPicSearch/assets/9484642/8443d7d3-5af0-4f1b-9660-51da5931f5de)

**Comment by SEAFHMC** [comment]
更新了一下saucenao的token解决了【

**Comment by NekoAria** [comment]
事实上有相关配置吧：https://github.com/NekoAria/YetAnotherPicSearch/blob/99fda30db7445119f891e6a4a2ade8541d100c89/YetAnotherPicSearch/config.py#L44-45

另外 `显示使用Ascii2D模式搜图但并没有搜` ，你确定吗？还是说只是消息没发出来。
