### ISSUE TITLE
下载失败，可能是pip版本原因？

### ISSUE THREAD

**Issue by Moekey114514** [NekoAria/YetAnotherPicSearch#15]
![image](https://user-images.githubusercontent.com/48763754/181199194-87573e81-c1de-4e62-9dd9-973afb5e84b4.png)
如上图

**Comment by Moekey114514** [comment]
pip install YetAnotherPicSearch和nb plugin install YetAnotherPicSearch都试过，报的错是一样的

**Comment by NekoAria** [comment]
Python 版本是多少呢？

**Comment by Moekey114514** [comment]
是3.8.5

**Comment by NekoAria** [comment]
我已经降低了要求的 Python 版本到 3.8 ，你再安装试试。

**Comment by Moekey114514** [comment]
使用nb plugin install YetAnotherPicSearch下载成功了，感谢_(:з」∠)_
