### ISSUE TITLE
搜图失败 TypeError

### ISSUE THREAD

**Issue by EnderHane** [NekoAria/YetAnotherPicSearch#16]
### YetAnotherPicSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

YetAnotherPicSearch 1.5.16
go-cqhttp 1.0.0-rc3
nonebot 2.0.0-beta.4
Python 3.10.5
Debian 11.4

### 如何复现

本人使用此图片**私聊**搜图稳定触发：
https://raw.githubusercontent.com/EnderHane/randomrepo/main/FL8LMtsVQAIC6CZ.jpg

### 实际行为

![报错聊天记录](https://raw.githubusercontent.com/EnderHane/randomrepo/main/202207311821-00.jpg)
![报错日志](https://raw.githubusercontent.com/EnderHane/randomrepo/main/202207311822-00.jpg)

**Comment by NekoAria** [comment]
请通过执行 `pip install -U PicImageSearch` 来更新搜图库的依赖版本
