### ISSUE TITLE
api已经配置好，但是SauceNAO无法使用，输入指令搜图--anime，任何图的结果总是会附带一连串的宠物小精灵照片

### ISSUE THREAD

**Issue by dingzhenbaohujiaran** [NekoAria/YetAnotherPicSearch#28]
### YetAnotherPicSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

YetAnotherPicSearch：1.6.0         go-cqhttp：1.0.0-rc3
nonebot：2.0.0beta.5                  python: 3.8
WindowsServer2012R2

### 列出安装的 Python 包

aiocache==0.11.1
aiodns==3.0.0
aiofiles==0.8.0
aiohttp==3.8.1
aiosignal==1.2.0
anyio==3.6.1
APScheduler==3.9.1
arrow==1.2.2
asgiref==3.5.2
async-timeout==4.0.2
attrs==21.4.0
backports.zoneinfo==0.2.1
bbcode==1.1.0
beautifulsoup4==4.11.1
binaryornot==0.4.4
Brotli==1.0.9
cchardet==2.1.7
certifi==2022.5.18.1
cffi==1.15.1
chardet==5.0.0
charset-normalizer==2.0.12
click==8.1.3
cn2an==0.5.17
colorama==0.4.4
cookiecutter==1.7.3
cssselect==1.1.0
cycler==0.11.0
diskcache==5.4.0
emoji==1.7.0
fastapi==0.79.0
feedparser==6.0.10
fonttools==4.33.3
frozenlist==1.3.0
greenlet==1.1.2
h11==0.12.0
h2==4.1.0
hpack==4.0.0
httpcore==0.15.0
httptools==0.4.0
httpx==0.23.0
httpx-socks==0.7.3
hyperframe==6.0.1
idna==3.3
imageio==2.19.2
importlib-metadata==4.12.0
jieba==0.42.1
Jinja2==3.1.2
jinja2-time==0.2.0
kiwisolver==1.4.3
loguru==0.6.0
lxml==4.9.1
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.5.2
msgpack==1.0.3
multidict==6.0.2
nb-cli==0.6.7
nonebot-adapter-onebot==2.1.3
nonebot-plugin-abbrreply==1.1.2
nonebot-plugin-abstract==1.0.5
nonebot-plugin-apscheduler==0.1.2
nonebot-plugin-crazy-thursday==0.2.3
nonebot-plugin-heweather==0.6.0
nonebot-plugin-hikarisearch==0.1.6
nonebot-plugin-htmlrender==0.1.1
nonebot-plugin-imageutils==0.1.6.3
nonebot-plugin-memes==0.3.2
nonebot-plugin-moyu==0.3.0
nonebot-plugin-petpet==0.3.5
nonebot-plugin-picsearcher==0.1.8rc1
nonebot-plugin-pixiv==1.0.7
nonebot-plugin-pixivrank-search==0.6
nonebot-plugin-read-60s==0.2.3
nonebot-plugin-remake==0.2.4
nonebot-plugin-setu==1.1.1
nonebot-plugin-smart-reply==0.0.5
nonebot2==2.0.0b5
numpy==1.22.3
opencv-python==4.5.5.64
opencv-python-headless==4.5.5.64
packaging==21.3
picimagesearch==3.3.11
Pillow==9.1.1
pinyin==0.4.0
playwright==1.24.1
poyo==0.5.0
proces==0.1.2
prompt-toolkit==3.0.30
pycares==4.2.2
pycparser==2.21
pydantic==1.9.1
pyee==8.1.0
pyfiglet==0.8.post1
Pygments==2.12.0
pygtrie==2.4.2
pymdown-extensions==9.5
pyparsing==3.0.9
pyquery==1.4.3
python-dateutil==2.8.2
python-dotenv==0.20.0
python-markdown-math==0.8
python-slugify==6.1.2
python-socks==2.0.3
pytz==2022.1
pytz-deprecation-shim==0.1.0.post0
PyYAML==6.0
requests==2.28.1
rfc3986==1.5.0
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.6
sgmllib3k==1.0.0
six==1.16.0
sniffio==1.2.0
soupsieve==2.3.2.post1
starlette==0.19.1
tenacity==8.0.1
text-unidecode==1.3
tomlkit==0.10.2
tqdm==4.64.0
typing_extensions==4.2.0
tzdata==2022.1
tzlocal==4.2
ujson==5.3.0
urllib3==1.26.9
uvicorn==0.18.2
watchfiles==0.16.1
watchgod==0.8.2
wcwidth==0.2.5
webdav4==0.9.7
websockets==10.1
win32-setctime==1.1.0
yarl==1.8.1
yetanotherpicsearch==1.6.0
youth-version-of-setu4==0.0.9
zhconv==1.4.3
zipp==3.8.1

### 如何复现

![故障1](https://user-images.githubusercontent.com/105736187/184637942-871127fd-7a4b-4513-b628-43c803e36d1b.jpg)
![故障2](https://user-images.githubusercontent.com/105736187/184637950-e7be18db-6d95-472d-8340-2b68472df9c6.jpg)
![故障3](https://user-images.githubusercontent.com/105736187/184637957-b81f5b2c-1077-4dd9-b60c-ce7c967a2022.jpg)
输入指令搜图--anime 总是会出现一连串的宠物小精灵图片（使用了不同的图片，结果还是一样会发出该宠物小精灵图片），另外sauceNao也已经搭建了API，但是一直显示暂时无法使用

### 期望行为

不再重复一连串宠物小精灵图片

### 实际行为

重复了一连串宠物小精灵图片，且运行过程没有出现异常信息

**Comment by NekoAria** [comment]
无法复现，能把日志贴一下吗？
而且那个格式并不是这个插件返回的格式。
我怀疑是其他插件的回应。
至于 SauceNao 一直显示暂时无法使用，推测是你网络环境的问题，考虑配置代理 proxy 。

**Comment by dingzhenbaohujiaran** [comment]
> 无法复现，能一下吗？ 而另一种插件另一种方式返回返回格式 网络环境 是其他的响应。 。

08-16 00:11:02 [SUCCESS] nonebot | ONEBOT V11 3144903834 | [message.private.friend]: Message -1068217450 from 1994802450 "搜图-anime"
08-16 00:11:02 [INFO] nonebot | Event will be handled by <Matcher from YetAnotherPicSearch, type=message, priority=5, temp=False>
08-16 00:11:02 [INFO] nonebot | Matcher <Matcher from YetAnotherPicSearch, type=message, priority=5, temp=False> running complete
08-16 00:11:02 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_smart_reply, type=message, priority=99, temp=False>
08-16 00:11:04 [INFO] nonebot_plugin_smart_reply | 来自小爱同学的智能回复: 搜不到搜不到
08-16 00:11:04 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_smart_reply, type=message, priority=99, temp=False> running complete
08-16 00:11:07 [SUCCESS] nonebot | ONEBOT V11 3144903834 | [message.private.friend]: Message -1219265792 from 1994802450 "[CQ:image,file=80cf9fc13581fc33c4a06ac16bce92b3.image,url=https://c2cpicdw.qpic.cn/offpic_new/1994802450//1994802450-426652077-80CF9FC13581FC33C4A06AC16BCE92B3/0?term=3]"
08-16 00:11:07 [INFO] nonebot | Event will be handled by <Matcher from YetAnotherPicSearch, type=message, priority=0, temp=True>
08-16 00:11:10 [INFO] nonebot | Matcher <Matcher from YetAnotherPicSearch, type=message, priority=0, temp=True> running complete

我看了一下是另一个pixiv插件导致的一连串的小精灵图片，但是现在那个SauceNao还是无法使用，运行这边也没有报任何差错
![api配置](https://user-images.githubusercontent.com/105736187/184673892-ae28c4f9-d119-4967-a762-70078fded457.png)

**Comment by dingzhenbaohujiaran** [comment]
> 无法复现，能把日志贴一下吗？ 而且那个格式并不是这个插件返回的格式。 我怀疑是其他插件的回应。 至于 SauceNao 一直显示暂时无法使用，推测是你网络环境的问题，考虑配置代理 proxy 。
![搜图](https://user-images.githubusercontent.com/105736187/184674669-a9c2e2b2-a5c3-44b3-964e-af3634405e9b.png)

**Comment by NekoAria** [comment]
https://github.com/NekoAria/YetAnotherPicSearch/blob/6f9b9828d77893b7875cb9dd6849ecd01b8fa252/YetAnotherPicSearch/saucenao.py#L110

你往这行下面添加这些：

```Python
from nonebot.log import logger
logger.info(f"HTTP status code: {res.status}")
logger.info(f"SauceNao response: {res.origin}")
```

重启机器人后再发图片搜图，然后把对应的日志发一下。

**Comment by dingzhenbaohujiaran** [comment]
> https://github.com/NekoAria/YetAnotherPicSearch/blob/6f9b9828d77893b7875cb9dd6849ecd01b8fa252/YetAnotherPicSearch/saucenao.py#L110
> 
> 你往这行下面添加这些：
> 
> ```python
> from nonebot.log import logger
> logger.info(f"HTTP status code: {res.status}")
> logger.info(f"SauceNao response: {res.origin!r}")
> ```
> 
> 重启机器人后再发图片搜图，然后把对应的日志发一下。
![搜图2](https://user-images.githubusercontent.com/105736187/184678879-c648e333-e7b2-473b-acb8-e1998d56442c.png)

08-16 00:46:04 [SUCCESS] nonebot | Running NoneBot...
08-16 00:46:04 [INFO] uvicorn | Started server process [7988]
08-16 00:46:04 [INFO] uvicorn | Waiting for application startup.
08-16 00:46:04 [INFO] nonebot_plugin_memes | 正在检查资源文件...
08-16 00:46:04 [INFO] nonebot_plugin_apscheduler | Scheduler Started
08-16 00:46:04 [INFO] uvicorn | Application startup complete.
08-16 00:46:04 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:52341 (Press CTRL+C to quit)
08-16 00:46:04 [INFO] uvicorn | ('127.0.0.1', 63652) - "WebSocket /onebot/v11/ws/" [accepted]
08-16 00:46:04 [INFO] nonebot | OneBot V11 | Bot 3144903834 connected
08-16 00:46:04 [INFO] websockets | connection open
08-16 00:46:04 [INFO] nonebot | Event will be handled by <Matcher from YetAnotherPicSearch, type=meta_event, priority=1,
 temp=True>
08-16 00:46:04 [INFO] nonebot | Matcher <Matcher from YetAnotherPicSearch, type=meta_event, priority=1, temp=True> runni
ng complete
08-16 00:46:10 [SUCCESS] nonebot | ONEBOT V11 3144903834 | [message.private.friend]: Message 1649543140 from 1994802450
"搜图"
08-16 00:46:10 [INFO] nonebot | Event will be handled by <Matcher from YetAnotherPicSearch, type=message, priority=5, te
mp=False>
08-16 00:46:10 [INFO] nonebot | Matcher <Matcher from YetAnotherPicSearch, type=message, priority=5, temp=False> running
 complete
08-16 00:46:10 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_smart_reply, type=message, priorit
y=99, temp=False>
08-16 00:46:13 [INFO] nonebot_plugin_smart_reply | 来自小爱同学的智能回复: 搜什么图
08-16 00:46:13 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_smart_reply, type=message, priority=99, temp=False>
 running complete
08-16 00:46:16 [SUCCESS] nonebot | ONEBOT V11 3144903834 | [message.private.friend]: Message 357906290 from 1994802450 "
[CQ:image,file=80cf9fc13581fc33c4a06ac16bce92b3.image,url=https://c2cpicdw.qpic.cn/offpic_new/1994802450//1994802450-636
066037-80CF9FC13581FC33C4A06AC16BCE92B3/0?term=3]"
08-16 00:46:16 [INFO] nonebot | Event will be handled by <Matcher from YetAnotherPicSearch, type=message, priority=0, te
mp=True>
08-16 00:46:19 [INFO] nonebot | Matcher <Matcher from YetAnotherPicSearch, type=message, priority=0, temp=True> running
complete
![配置2](https://user-images.githubusercontent.com/105736187/184679159-6512b14f-b7d1-4fc6-84c3-f7d6de166d7a.png)

**Comment by NekoAria** [comment]
忘了提了，你要在搜图的时候额外带上 `--purge` 来不使用缓存，否则一直返回的是之前搜图的结果。

**Comment by dingzhenbaohujiaran** [comment]
> 忘了提了，你要在搜图的时候额外带上 `--purge` 来不使用缓存，否则一直返回的是之前搜图的结果。
![运行日志](https://user-images.githubusercontent.com/105736187/184680948-7d549e0f-7d10-4fca-97b9-f52c896c7821.png)

**Comment by NekoAria** [comment]
你这说明配置的 SauceNao api key 无效啊，重新注册一个？https://saucenao.com/user.php

**Comment by dingzhenbaohujiaran** [comment]
> 你这说明配置的 SauceNao api key 无效啊，重新注册一个？https://saucenao.com/user.php

终于成功了！谢谢你，今天百度搞了好久还是不知道什么原因，新手一个，感谢感谢。

**Comment by dingzhenbaohujiaran** [comment]
08-20 18:12:45 [SUCCESS] nonebot | Running NoneBot...
08-20 18:12:45 [INFO] uvicorn | Started server process [6976]
08-20 18:12:45 [INFO] uvicorn | Waiting for application startup.
08-20 18:12:45 [INFO] nonebot_plugin_petpet | 正在检查资源文件...
08-20 18:12:45 [INFO] nonebot_plugin_memes | 正在检查资源文件...
08-20 18:12:45 [INFO] nonebot_plugin_apscheduler | Scheduler Started
08-20 18:12:45 [INFO] uvicorn | Application startup complete.
08-20 18:12:45 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:52341 (Press CTRL+C to quit)
08-20 18:12:45 [INFO] uvicorn | ('127.0.0.1', 57168) - "WebSocket /onebot/v11/ws/" [accepted]
08-20 18:12:45 [INFO] nonebot | OneBot V11 | Bot 1994802450 connected
08-20 18:12:45 [INFO] websockets | connection open
08-20 18:12:45 [INFO] nonebot | Event will be handled by <Matcher from YetAnotherPicSearch, type=meta_event, priority=1,
 temp=True>
08-20 18:12:45 [INFO] nonebot | Matcher <Matcher from YetAnotherPicSearch, type=meta_event, priority=1, temp=True> runni
ng complete
08-20 18:12:53 [SUCCESS] nonebot | ONEBOT V11 1994802450 | [message.private.friend]: Message -2006454830 from 3144903834
 "搜图--purge"
08-20 18:12:53 [INFO] nonebot | Event will be handled by <Matcher from YetAnotherPicSearch, type=message, priority=5, te
mp=False>
08-20 18:12:53 [INFO] nonebot | Matcher <Matcher from YetAnotherPicSearch, type=message, priority=5, temp=False> running
 complete
08-20 18:13:51 [SUCCESS] nonebot | ONEBOT V11 1994802450 | [message.private.friend]: Message -1731555144 from 3144903834
 "[CQ:image,file=cd539f0681e821447e6ad15f297b767e.image,url=https://c2cpicdw.qpic.cn/offpic_new/3144903834//3144903834-2
220527477-CD539F0681E821447E6AD15F297B767E/0?term=3]"
08-20 18:13:51 [INFO] nonebot | Event will be handled by <Matcher from YetAnotherPicSearch, type=message, priority=0, te
mp=True>
08-20 18:13:58 [INFO] nonebot | Matcher <Matcher from YetAnotherPicSearch, type=message, priority=0, temp=True> running
complete

后面多次换了API突然无法使用，但是运行日志这里没有提示错误
