### ISSUE TITLE
搜图报错

### ISSUE THREAD

**Issue by xh22805** [NekoAria/YetAnotherPicSearch#30]
### YetAnotherPicSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

系统:windows 11，Python 版本3.10，nonebot2 b4，cqhttp rc3，YetAnotherPicSearch 1.6.3

### 列出安装的 Python 包

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

aiocache==0.11.1
--
aiocqhttp==1.4.3
aiodns==3.0.0
aiohttp==3.8.1
aiosignal==1.2.0
arrow==1.2.2
async-timeout==4.0.2
baike==1.5.0
bbcode==1.1.0
binaryornot==0.4.4
blinker==1.4
Brotli==1.0.9
CacheControl==0.12.11
cachetools==5.2.0
cachy==0.3.0
cchardet==2.1.7
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.1.0
cleo==0.8.1
clikit==0.6.2
cookiecutter==1.7.3
crashtest==0.3.1
cssselect==1.1.0
decorator==5.1.1
deep-translator==1.8.3
diskcache==5.4.0
distlib==0.3.4
emoji==1.7.0
exception==0.1.0
expandvars==0.9.0
filelock==3.7.1
frozenlist==1.3.0
h2==4.1.0
hpack==4.0.0
html5lib==1.1
hypercorn==0.13.2
hyperframe==6.0.1
idna==3.3
ImageHash==4.2.1
imageio==2.19.3
itsdangerous==2.1.2
jarowinkler==1.2.1
jieba==0.42.1
Jinja2==3.1.2
jinja2-time==0.2.0
keyring==23.6.0
Levenshtein==0.20.2
lockfile==0.12.2
lxml==4.9.1
Markdown==3.3.7
MarkupSafe==2.1.1
msgpack==1.0.4
multipart==0.2.4
nb-cli==0.6.7
nonebot-plugin-draw==0.1.2
nonebot-plugin-guild-patch==0.2.0
nonebot-plugin-htmlrender==0.0.5
nonebot-plugin-imageutils==0.1.6.3
nonebot-plugin-manager==0.5.9
nonebot-plugin-memes==0.3.2
nonebot-plugin-moyu==0.3.0
nonebot-plugin-remake==0.2.5
nonebot-plugin-shindan==0.2.4
opencv-python-headless==4.6.0.66
pastel==0.2.1
pexpect==4.8.0
picimagesearch==3.3.11
pinyin==0.4.0
pkginfo==1.8.3
platformdirs==2.5.2
poetry==1.1.14
poetry-core==1.0.8
poyo==0.5.0
priority==2.0.0
prompt-toolkit==3.0.29
ptyprocess==0.7.0
pycares==4.2.2
pycparser==2.21
pyfiglet==0.8.post1
pylev==1.4.0
pymdown-extensions==9.5
pyparsing==3.0.9
pyquery==1.4.3
python-markdown-math==0.8
python-multipart==0.0.5
python-slugify==6.1.2
pywin32-ctypes==0.2.0
qbittorrent==0.1.6
quart==0.17.0
rapidfuzz==2.5.0
requests==2.28.1
requests-toolbelt==0.9.1
retry==0.9.2
retrying==1.3.3
scipy==1.6.1
sentry-sdk==1.5.12
sgmllib3k==1.0.0
shellingham==1.4.0
six==1.16.0
SQLAlchemy==1.3.24
tenacity==8.0.1
text-unidecode==1.3
thefuzz==0.19.0
tinydb==4.7.0
toml==0.10.2
urllib3==1.26.10
virtualenv==20.15.1
watchfiles==0.16.1
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==2.1.2
wordcloud==1.8.2.2
wsproto==1.1.0
zhconv==1.4.3

</body>

</html>

### 如何复现

![Screenshot_20220824_125659](https://user-images.githubusercontent.com/104178374/186332976-46bfd6f8-9693-4fce-94c6-72f362537af2.jpg)

### 实际行为

![Uploading 图片.png…]()

**Comment by xh22805** [comment]
<img width="813" alt="屏幕截图 2022-08-24 130504" src="https://user-images.githubusercontent.com/104178374/186333389-7c0a82b5-cb14-4349-b10c-70ac4df29339.png">

**Comment by NekoAria** [comment]
你试试最新的代码，如果你不是通过 pip 或 nb-cli 下载的，直接下最新的 `__init__.py` 覆盖本地的。
否则用 `pip install git+https://github.com/NekoAria/YetAnotherPicSearch.git@311ae81558d90be46ea1245928e0219333298e0d` 安装。

**Comment by xh22805** [comment]
解决了,谢谢大佬

**Comment by NekoAria** [comment]
从 #32 的讨论结果来看， 这个问题和具体的 Windows 版本也有关系。
麻烦你把下面这段代码的执行结果贴一下：

```Python
import platform
import sys

print(platform.platform())
print(sys.getwindowsversion())
```

**Comment by xh22805** [comment]
![Screenshot_20220829_232113](https://user-images.githubusercontent.com/104178374/187236299-1551c15e-9054-40fb-b748-8661d13a0218.jpg)
问题好像是出在搜图的api上，搜图的api会变，要重新输入才能用

**Comment by NekoAria** [comment]
> 

没懂你指的是什么。。
搜图的 API 是指 PicImageSearch 还是？
要重新输入什么才能用？

**Comment by xh22805** [comment]
全局配置的

**Comment by NekoAria** [comment]
还是没理解你想表达什么（

**Comment by xh22805** [comment]
和现在这个问题没有关系...

**Comment by xh22805** [comment]
...emm,该怎么解释呢，就是
# issue 30
if sys.version_info >= (3, 8) and sys.platform == "win32":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
这个代码可以不加，上次那个报错不是这个问题引起的

**Comment by NekoAria** [comment]
> ...emm,该怎么解释呢，就是
> # issue 30
> 
> if sys.version_info >= (3, 8) and sys.platform == "win32": asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy()) 这个代码可以不加，上次那个报错不是这个问题引起的

好吧，那先去掉了。如果之后再遇到这个问题再说。
