### ISSUE TITLE
在添加了ex的cookie之后，搜索结果一直为空

### ISSUE THREAD

**Issue by Wrs-01** [NekoAria/YetAnotherPicSearch#31]
### YetAnotherPicSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

YetAnotherPicSearch  1.6.3
go-cqhttp [v1.0.0-rc3]
nonebot 2.0.0b5
Python 3.10.5
OS windows

### 如何复现

输入 exhentai_cookies: str = "ipb_member_id=4663296; ipb_pass_hash=4a33d2ddfbca990b1b2d02295a8fe8ae; igneous=1ceb6a6d9; sk=e9k8i3ic6hdvnagdgdsruj03nhc2" 后，使用 /搜图  --ex 指令bot全部返回搜索结果为空
但是底下的搜索页面点进去却有内容

代码无任何报错

### 实际行为

![image](https://user-images.githubusercontent.com/82505428/186543151-f62225fe-55cd-4ad0-8779-0e677535c587.png)
![image](https://user-images.githubusercontent.com/82505428/186543178-44a4097a-39e6-40f0-b861-4fb89c1cb785.png)
![image](https://user-images.githubusercontent.com/82505428/186543345-4aabd002-33d0-4842-a1c1-d1d706334ef4.png)

**Comment by NekoAria** [comment]
感谢反馈，是搜索结果的解析逻辑不正确。

**Comment by devil233-ui** [comment]
> 感谢反馈，是搜索结果的解析逻辑不正确。

请问现在是不是失效了？

![Image](https://github.com/user-attachments/assets/fcb07dc1-8f11-42e0-bcf6-99ce15dc0c26)

![Image](https://github.com/user-attachments/assets/2b62149c-459a-4b25-b4d2-b54d08d209f7)

**Comment by devil233-ui** [comment]
好的感谢回复，也建议在readme说明下
