### ISSUE TITLE
后台奇怪报错

### ISSUE THREAD

**Issue by liuzj288** [NekoAria/YetAnotherPicSearch#38]
### YetAnotherPicSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

v1.6.11

### 如何复现

![image](https://user-images.githubusercontent.com/13833404/191157040-d1dfe3ea-df35-4515-a06b-3f66059883d3.png)

### 实际行为

![image](https://user-images.githubusercontent.com/13833404/191157171-3d23620f-9c5b-4cb9-9ceb-4d1c2e070e0a.png)

**Comment by NekoAria** [comment]
这个不是因为另一个插件 [nonebot-plugin-chatrecorder](https://github.com/noneplugin/nonebot-plugin-chatrecorder) 引起的吗？
你先禁用或者去掉这个插件在试试？
