### ISSUE TITLE
搜图结果发两遍

### ISSUE THREAD

**Issue by KarisAya** [NekoAria/YetAnotherPicSearch#40]
### YetAnotherPicSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

YetAnotherPicSearch 最新的
go-cqhttp 最新的
nonebot2 v11
Python 3.10.7

### 列出安装的 Python 包

与hikarisearch一起使用，不过估计不是这个问题。

### 如何复现

搜图

### 实际行为

![Screenshot_20220927-090042](https://user-images.githubusercontent.com/51886078/192407285-6d1234b7-863f-4216-9815-567e7b007b90.jpg)

**Comment by NekoAria** [comment]
有日志吗？
是就触发一次还是每次搜图都会触发？

**Comment by KarisAya** [comment]
> 有日志吗？ 是就触发一次还是每次搜图都会触发？

测试了一下，好像是因为回复搜图+图片同时atbot会同时触发IMAGE_SEARCH和IMAGE_SEARCH_MODE，所以私聊搜图必发两遍，私聊发图片是正常的。群里搜图tome了也会发两遍。

**Comment by NekoAria** [comment]
如果你习惯私聊的时候发`搜图`指令，那你可以把配置项 `search_immediately` 设为 False 。

**Comment by NekoAria** [comment]
> 群里搜图tome了也会发两遍。

呃，那还是修一下吧（
