### ISSUE TITLE
有没有办法让他返回的图是原图

### ISSUE THREAD

**Issue by jinxx52** [NekoAria/YetAnotherPicSearch#5]
如题 缩略图的话还要去原地址手动保存

**Comment by NekoAria** [comment]
> 如题 缩略图的话还要去原地址手动保存

虽然看起来好像很简单，但是具体来说，需要考虑一些情况：

1. 有些搜图结果是动图或视频，而不是静态的图片
2. 有些原图、动图或视频尺寸过大，会超过发送上限
3. 有些搜图结果的地址已经无法访问（尤其是那些被原作者删除了的）
4. ......

所以具体来说要实现这个需要考虑的问题还不少。而已经给了搜图结果地址的情况下，本来点一下链接就行的，却需要考虑上面种种情况，我觉得得不偿失。

**Comment by jinxx52** [comment]
晓得了 谢谢
