### ISSUE TITLE
安装成功，启动失败

### ISSUE THREAD

**Issue by Luzhopo** [NekoAria/YetAnotherPicSearch#6]
由于使用 nb 安装失败，所以采用 pip 安装，按照部署教程在.env.prod里协商代码后启动，提示启动失败
![WX4@01)038N@TL6AY{NY853](https://user-images.githubusercontent.com/98378907/169629206-11a7e8a2-a7eb-4025-9775-3d2667c50efc.png)
求解决

**Comment by NekoAria** [comment]
请你把完整的 `bot.py` 贴出来

**Comment by Luzhopo** [comment]
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import nonebot
from nonebot.adapters.onebot.v11 import Adapter as ONEBOT_V11Adapter

# Custom your logger
# 
# from nonebot.log import logger, default_format
# logger.add("error.log",
#            rotation="00:00",
#            diagnose=False,
#            level="ERROR",
#            format=default_format)

# You can pass some keyword args config to init function
nonebot.init()
app = nonebot.get_asgi()

driver = nonebot.get_driver()
driver.register_adapter(ONEBOT_V11Adapter)

nonebot.load_builtin_plugins("echo")
nonebot.load_plugin('nonebot_plugin_picsearcher')
nonebot.load_plugin("nonebot_plugin_guess")
nonebot.load_plugin('nonebot-plugin-ncm')
nonebot.load_plugin("nonebot_plugin_setu_now")
nonebot.load_plugin("YetAnotherPicSearch")           #在这里

# Please DO NOT modify this file unless you know what you are doing!
# As an alternative, you should use command `nb` or modify `pyproject.toml` to load plugins
nonebot.load_from_toml("pyproject.toml")

# Modify some config / config depends on loaded configs
# 
# config = driver.config
# do something...


if __name__ == "__main__":
    nonebot.logger.warning("Always use `nb run` to start the bot instead of manually running!")
    nonebot.run(app="__mp_main__:app")

##请您指导

**Comment by NekoAria** [comment]
请你用 `pip show YetAnotherPicSearch` 来确认此插件是否安装成功

**Comment by Luzhopo** [comment]
bot.py代码
![bot1](https://user-images.githubusercontent.com/98378907/169651717-c65cfd48-283e-447f-a8cb-cf008aeba9d0.png)
使用‘pip show YetAnotherPicSearch’所得结果
![bot2](https://user-images.githubusercontent.com/98378907/169651718-d80dbd64-4c35-4da7-a52c-1178788d3330.jpg)
请您指导

**Comment by NekoAria** [comment]
光这样看没看出有什么问题，而且我也没办法复现，有可能是安装的依赖之间有冲突吧。
你试试卸载再安装： `pip uninstall YetAnotherPicSearch`  `pip install YetAnotherPicSearch`
然后把这个过程贴出来。

**Comment by Luzhopo** [comment]
![bot2](https://user-images.githubusercontent.com/98378907/169653439-d3af14d7-3667-428e-9b08-77366e4ec795.png)

**Comment by NekoAria** [comment]
然后 `nb run` 还是报一开始那个找不到模块的错误吗？

**Comment by Luzhopo** [comment]
是的

**Comment by kitUIN** [comment]
> 是的

你装错地方了,你机器人运行环境是3.8,而你装插件用的是3.10

**Comment by NekoAria** [comment]
> > 是的
> 
> 你装错地方了,你机器人运行环境是3.8,而你装插件用的是3.10

没注意到环境问题。。

**Comment by Luzhopo** [comment]
> 
@。@我的我的。现在成功了，非常感谢各位的帮助

**Comment by Luzhopo** [comment]
> > > 是的
> > 
> > 
> > 你装错地方了,你机器人运行环境是3.8,而你装插件用的是3.10
> 
> 没注意到环境问题。。

@。@我的我的，现在成功了，非常感谢各位的帮助
