### ISSUE TITLE
最新插件机器人没反应

### ISSUE THREAD

**Issue by TomorrowLost** [NekoAria/YetAnotherPicSearch#63]
### YetAnotherPicSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

最新版本  python 3.9.15 

### 如何复现

没有反应 能接收到指令 发过去的图 没反应

### 实际行为

没有反应 能接收到指令 发过去的图 没反应

**Comment by NekoAria** [comment]
可能是 pixiv.net 又被加入红链了，你往配置文件里加入这个：

```
to_confuse_urls=["danbooru.donmai.us", "konachan.com", "pixiv.net"]
```

然后重启机器人，再试试。

**Comment by TomorrowLost** [comment]
> 可能是 pixiv.net 又被加入红链了，你往配置文件里加入这个：
> 
> ```
> to_confuse_urls=["danbooru.donmai.us", "konachan.com", "pixiv.net"]
> ```
> 
> 然后重启机器人，再试试。

好了
