### ISSUE TITLE
回复纯文字消息并 @机器人 会触发搜图

### ISSUE THREAD

**Issue by tkgs0** [NekoAria/YetAnotherPicSearch#73]
### YetAnotherPicSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

YetAnotherPicSearch==1.7.11
go-cqhttp==1.0.0rc4
nonebot2==2.0.0rc3
Python 3.10
Debian 11

### 列出安装的 Python 包

aiodns==3.0.0
aiofiles==23.1.0
aiohttp==3.8.4
aiosignal==1.3.1
anyio==3.6.2
APScheduler==3.9.1.post1
arrow==1.2.3
async-timeout==4.0.2
attrs==22.2.0
bbcode==1.1.0
beautifulsoup4==4.11.1
binaryornot==0.4.4
Brotli==1.0.9
cachetools==5.3.0
cashews==5.0.0
certifi==2022.12.7
cffi==1.15.1
chardet==5.1.0
charset-normalizer==2.1.1
click==8.1.3
contourpy==1.0.7
cookiecutter==2.1.1
cssselect==1.2.0
cycler==0.11.0
DBUtils==3.0.2
deep-translator==1.10.0
diskcache==5.4.0
distlib==0.3.6
docx2txt==0.8
emoji==2.2.0
fastapi==0.89.1
feedparser==6.0.10
filelock==3.9.0
fonttools==4.38.0
frozenlist==1.3.3
h11==0.12.0
httpcore==0.14.7
httptools==0.5.0
httpx==0.22.0
idna==3.4
ImageHash==4.3.1
Jinja2==3.1.2
jinja2-time==0.2.0
kiwisolver==1.4.4
langid==1.1.6
loguru==0.6.0
lxml==4.9.2
magneturi==1.3
MarkupSafe==2.1.2
matplotlib==3.6.3
msgpack==1.0.4
multidict==6.0.4
nb-cli==1.0.4
nonebot-adapter-onebot==2.2.1
nonebot-plugin-apscheduler==0.2.0
nonebot-plugin-guild-patch==0.2.2
nonebot-plugin-imageutils==0.1.14
nonebot2==2.0.0rc3
noneprompt==0.1.7
numpy==1.24.1
opencv-python-headless==4.7.0.68
packaging==23.0
picimagesearch==3.7.8
pikpakapi==0.1.1
Pillow==9.4.0
platformdirs==2.6.2
poyo==0.5.0
prompt-toolkit==3.0.36
psutil==5.9.4
pycares==4.3.0
pycparser==2.21
pydantic==1.10.4
pydub==0.25.1
pyfiglet==0.8.post1
pygtrie==2.5.0
pyparsing==3.0.9
pypdf==3.4.1
pyquery==2.0.0
python-dateutil==2.8.2
python-dotenv==0.21.1
python-slugify==7.0.0
pytz==2022.7.1
pytz-deprecation-shim==0.1.0.post0
PyWavelets==1.4.1
PyYAML==6.0
requests==2.28.2
rfc3986==1.5.0
scipy==1.10.0
sgmllib3k==1.0.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.3.2.post1
starlette==0.22.0
tenacity==8.2.1
text-unidecode==1.3
tinydb==4.7.1
tomlkit==0.11.6
typing_extensions==4.4.0
tzdata==2022.7
tzlocal==4.2
ujson==5.7.0
urllib3==1.26.14
uvicorn==0.20.0
uvloop==0.17.0
virtualenv==20.17.1
watchfiles==0.18.1
wcwidth==0.2.6
websockets==10.4
yarl==1.8.2

### 如何复现

回复 `纯文字消息` 并 `@机器人` , 会触发 `请发送图片`

### 期望行为

在 `@机器人` 的回复消息中未检测到图片, 并且未检测到 `搜图` 关键字时不触发搜图

### 实际行为

![Screenshot_20230214_084554_com tencent mobileqq](https://user-images.githubusercontent.com/107618388/218612475-e76c0665-2867-44d3-a6e2-f01430dc7ed2.jpg)

**Comment by NekoAria** [comment]
感谢反馈。修好了，顺便把触发条件的逻辑严格化了，应该没问题了。
请你更新后帮忙再多测试测试。

**Comment by tkgs0** [comment]
感谢作者🥰, 更新后问题解决了
