### ISSUE TITLE
能否添加配置项更改搜图触发方式

### ISSUE THREAD

**Issue by WindraiteLesd** [NekoAria/YetAnotherPicSearch#76]
### 功能需求

添加开关让插件只通过指令和关键词触发，不响应at回复的图片，或者可以切换模式

### 理由

有人反馈私聊bot只发送图片有概率会误触发搜图，以及进群时有q群管家自动欢迎时at发送的图片也会触发搜图

**Comment by NekoAria** [comment]
前一个可以配置 `search_immediately` 为 false 来解决，私聊发送图片不会立即搜图，需要带指令。

后一个我不确定你想表达的意思，能否贴个截图？

**Comment by WindraiteLesd** [comment]
![IMG_20230224_120203](https://user-images.githubusercontent.com/104503043/221088938-817c015e-3c68-4ad9-baaf-b7ad02f27845.jpg)
像这种，q群管家欢迎语里带图片的

**Comment by NekoAria** [comment]
那就加个配置，启用后只能使用指令或关键词触发，这样相关逻辑的修改也比较简单。

**Comment by NekoAria** [comment]
发了一个新版本 `v1.8.0` ，你试试？
依赖有所变动，需要更新一下。

**Comment by WindraiteLesd** [comment]
no module name _gdbm

**Comment by NekoAria** [comment]
> no module name _gdbm

能把你的 python 版本和这个报错的日志贴一下吗？

**Comment by WindraiteLesd** [comment]
> > no module name _gdbm
> 
> 能把你的 python 版本和这个报错的日志贴一下吗？ 好像是 Ubuntu 特有的问题，试试 `pip install python3-gdbm` ？
不，我用的是Windows Server 2019，Python 3.9.7
![IMG_20230224_165643](https://user-images.githubusercontent.com/104503043/221136074-e31af6e7-da37-4fea-a42c-3653b04ca579.jpg)

**Comment by NekoAria** [comment]
不对啊，我试了下在 Windows 上可以用 shelved_cache 。

**Comment by NekoAria** [comment]
原来是因为 5 天前的一个更新，那改一下依赖版本， 0.2.1 。

**Comment by WindraiteLesd** [comment]
不小心按到关闭了，刚才重装了插件一遍发现还是这个问题

**Comment by NekoAria** [comment]
> 不小心按到关闭了，刚才重装了插件一遍发现还是这个问题

什么问题？还是找不到那个包吗？。。
你先执行 `conda info shelved_cache` 看看版本对不对。

**Comment by WindraiteLesd** [comment]
> > 不小心按到关闭了，刚才重装了插件一遍发现还是这个问题
> 
> 什么问题？还是找不到那个包吗？。。 你先执行 `conda info shelved_cache` 看看版本对不对。
> 
> 不过看你发的截图路径来看，你似乎用的是 pip 安装？ (我没用过 conda )

是pip安装的，conda根本找不到这个包
![IMG_20230224_231612](https://user-images.githubusercontent.com/104503043/221215675-7f9fd8fd-916a-4572-baf4-348d8bdf413a.jpg)

**Comment by WindraiteLesd** [comment]
> > 不小心按到关闭了，刚才重装了插件一遍发现还是这个问题
> 
> 什么问题？还是找不到那个包吗？。。 你先执行 `conda info shelved_cache` 看看版本对不对。
> 
> 不过看你发的截图路径来看，你似乎用的是 pip 安装？ (我没用过 conda )

看来是版本不对，刚才发现用pip升级时会自动安装0.3.0版本的shelved_cache，降级为0.2.1后就正常了，但是pip那里却显示插件要求的版本是0.3.0，明明我看仓库的pyproject里写的版本是0.2.1...
