### ISSUE TITLE
新功能请求：NSFW结果过滤开关

### ISSUE THREAD

**Issue by Blue-Roar** [NekoAria/YetAnotherPicSearch#9]
如题，当前搜图功能在低相似度的情况下经常搜出R18内容，能否添加一个开关过滤掉R18结果

**Comment by NekoAria** [comment]
实际上这点很难做到，因为搜图结果里带 R18 区分的搜图引擎只有 whatanime 。
而默认的搜图用的是 saucenao ，低相似度自动调用的是 ascii2d ，这俩者都不区分是否为 R18 。
倒是可以加个判断和配置项，在低相似度的情况下不返回图片。
目前只有完全不返回图片的配置项。

**Comment by Blue-Roar** [comment]
saucenao的API里有一个hide=<0|1|2|3>参数不知道有没有效果？
“This controls the hidden field of results based on result content info. All results still show up in the api, check the hidden field for whether the site would have shown the image file.
0=show all, 1=hide expected explicit, 2=hide expected and suspected explicit, 3=hide all but expected safe. Default is 0.”
[原页面链接](https://saucenao.com/user.php?page=search-api)

**Comment by NekoAria** [comment]
> saucenao的API里有一个hide=<0|1|2|3>参数不知道有没有效果？ “0=show all, 1=hide expected explicit, 2=hide expected and suspected explicit, 3=hide all but expected safe. Default is 0.” [原页面链接](https://saucenao.com/user.php?page=search-api)

确实可行，不过他这里有4个值，严格程度依次递增。
那我另外再加一个配置项用来设定这个值。

**Comment by NekoAria** [comment]
发了一个新版本： [v1.5.6](https://github.com/NekoAria/YetAnotherPicSearch/releases/tag/1.5.6)

更新日志：

> ✨: 增加一个新的配置项用来隐藏 saucenao NSFW 搜索结果的缩略图
> 
> `saucenao_nsfw_hide_level`
> (对 saucenao 的搜索结果进行 NSFW 判断的严格程度(依次递增), 启用后自动隐藏相应的 NSFW 结果的缩略图：
> 0 表示不判断， 1 只判断明确的， 2 包括可疑的， 3 非明确为 SFW 的)
> 
> :arrow_up:: 依赖升级

**Comment by NekoAria** [comment]
又看了下，发现之前的实现逻辑写错了，重新发了个版本 v1.5.7 。
